---
output:
  html_document:
    theme: cosmo
params:
  fips: '01001'
  state_county_id: 'Alabama_test'
  county_name: 'test'
  state_name: 'Alabama'
title: "COVID-19 Risk calculator"
subtitle: '`r paste0("for ", params$county_name, " county, ",params$state_name)`' 
date: '`r Sys.time()`'
---

--------


```{r setup, echo=F, message=FALSE, warning=FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(ggiraph)
library(scales)
library(ggridges)

# Code display options
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=FALSE, echo = F, message=FALSE, warning=FALSE, fig.align="center", fig.retina = 2)

```

```{r}
df <- read_csv("data/current_county_cases_NYT.csv")

df_recent_sums_pop <- read_csv("data/current_county_pre_calc_prevalence.csv")

last_update <- as.Date("2020-05-05")

county_recent_cases <- (df_recent_sums_pop %>% filter(fips == params$fips))$recent_cases

county_recent_deaths <- (df_recent_sums_pop %>% filter(fips == params$fips))$recent_deaths

county_pop2019 <- (df_recent_sums_pop %>% filter(fips == params$fips))$pop2019

county_f_inf_rep <- (df_recent_sums_pop %>% filter(fips == params$fips))$f_inf_rep
```

This is a computationally generated report for this county. It uses recent COVID-19 case data that is curated by The New York Times and is available in their [github repository](https://github.com/nytimes/covid-19-data). We will calculate the percentage of people recently infected in this county and use that to estimate the chance of running into an infected person in a few different scenarios. This project was directly inspired by the work of [Joshua Weitz](https://twitter.com/joshuasweitz) at Georgia Tech.

## `r params$county_name` county has reported **`r county_recent_cases` cases** in the last 2 weeks

---

Let's start by looking at the cases reported in this county over time.

```{r}


ggplot(df %>% filter(fips == params$fips), aes(x = date, y = cases)) + geom_line()+geom_point() + 
  geom_vline(xintercept = last_update - days(14)) + theme_bw() + 
  labs(y = "Total cases", x = 'Date', 
       title = paste0("Total cases reported for ",params$county_name, " county over time"),
       caption = 'The black vertical line shows the two week mark. Data source: The New York Times') + 
  theme(plot.title = element_text(hjust = 0.5))

```

To calculate the percentage of the population that is reported infected in the last two weeks we can divide recent cases by the county population. The county reported **`r number(county_recent_cases, big.mark = ",")`** cases in the last two weeks and the 2019 population estimate for the county is **`r number(county_pop2019, big.mark = ",")`**.  

## Therefore **`r percent(county_f_inf_rep)`** of `r params$county_name` county has been reported infected

---

We calculated the same percentage for every county in the US, so let's see how this county compares.

```{r}

overall_med_f_inf_rep <- median(df_recent_sums_pop$f_inf_rep, na.rm = T)

percentile <- ecdf(df_recent_sums_pop$f_inf_rep)

county_percentile=percentile(county_f_inf_rep)

df_recent_sums_pop %>% 
  filter(f_inf_rep>0) %>% 
  mutate(current_county = ifelse(fips == params$fips, 25, 2)) %>% 
  ggplot(.) + geom_density_ridges(aes(x = f_inf_rep, y = 'US counties'), 
                                  jittered_points= T, position = 'raincloud', 
                                  point_shape = 21, point_alpha = 0.5, scale = 0.9) + 
  scale_x_log10(labels = scales::percent) +
  geom_vline(xintercept = overall_med_f_inf_rep) + 
  geom_vline(xintercept = (df_recent_sums_pop %>% filter(fips == params$fips))$f_inf_rep, color = 'red') + 
  labs(title = paste0("How does ",params$county_name," county prevalence compare to other US counties?"), y = NULL, x = 'Percent of county reported infected in last 2 weeks', 
       caption = 'Black line shows median county. Red line shows current county.') + theme_bw() + theme(plot.title = element_text(hjust = 0.5)) 

```

The above plot shows that the median US county reports a recent prevalence of **`r percent(overall_med_f_inf_rep)`**. `r params$county_name` county reports **`r percent(county_f_inf_rep)`**, which is higher than **`r percent(county_percentile)`** of all US counties.


## True cases are higher than reported cases

---

Practically, reported cases are a lower bound for the true cases and we can't really know the true number of cases in a county. Instead we can try to estimate the true number of cases crudely by looking at the death rate in each county. Sadly, the county reported **`r number(county_recent_deaths, big.mark = ",")`** deaths in the last two weeks. If we assumed cases and deaths were constant and that the death rate of COVID-19 is 1%, then we can estimate true cases as $(\text{deaths} * 100) / \text{cases}$. 

```{r}


#df_undercount <- df_recent_sums_pop %>% 
# filter(recent_cases >0 & recent_deaths >0) %>% 
#  mutate(undercount = ifelse(recent_cases >0 & recent_deaths >0, (recent_deaths*100) / recent_cases, NA))

overall_med_undercount <- median(df_recent_sums_pop$undercount, na.rm = T)

county_undercount <- (df_recent_sums_pop %>% filter(fips == params$fips))$undercount
                          

percentile <- ecdf(df_recent_sums_pop$undercount)

undercount_percentile=percentile(county_undercount)

fold_label <- function(x){
#e.g. 2 to 2x
  lab <- paste(x, "x", sep = '')
}

ggplot(df_recent_sums_pop) + 
  geom_vline(xintercept = 1, linetype = 2) + 
  geom_density_ridges(aes(x = undercount, y = 'US counties'), 
                                  jittered_points= T, position = 'raincloud', 
                      point_shape = 21, point_alpha = 0.5, scale = 0.9) + 
  geom_vline(xintercept = county_undercount, color = 'red') + 
  geom_vline(xintercept = overall_med_undercount)+
  scale_x_log10(labels = fold_label) +
#  geom_vline(xintercept = overall_med_f_inf_rep) + 
#  geom_vline(xintercept = (df_recent_sums_pop %>% filter(fips == params$fips))$f_inf_rep, color = 'red') + 
  labs(title = paste0("How does ",params$county_name," county undercounting compare to other US counties?"), y = NULL, x = 'True cases might be this many times higher', 
       caption = 'Black line shows median county. Red line shows current county.') + theme_bw() + theme(plot.title = element_text(hjust = 0.5)) 

```
Currently, most US counties are probably undercounting cases by a lot.

By this imperfect estimate, cases in `r params$county_name` county are being undercounted by **`r number((county_recent_deaths* 100) / county_recent_cases , big.mark = ",")`x**. This is not a precise estimate, but hopefully that gives you a sense for the uncertainty in the reported values. For now, let's just consider scenarios where there are actually 5x or 10x the number of reported cases in the county. 

## What is the chance of runing into an infected person?

---

As states reopen, we may wonder, "What is the chance someone around me is infected?" **Although the chance that any individual person is infected may remain small, as we interact with more and more people the chances go up dramatically.** Below is a plot to explore the chance that a subset of people within this county has at least one person infected. Simply, we can estimate this by calculating the probability that no one is infected. The remaining probability is the chance someone is infected. **[See here for more details.](https://scott-saunders.github.io/covid_risk_calculator/details.html)**

This calculation assumes that everyone is all mixed together and makes some other back of the envelope assumptions, but it can help us think about the situations we experience every day. 

* **Is it likely there is someone infected in this Target/Walmart? Grocery store?**
* **Could someone I passed on the street be infected?**
* **What's the chance someone in my apartment complex has COVID-19?**

The answers depend on how many people we are talking about (and the percentage of people infected). As you explore the plot below, think about these questions and how many people you encounter on a normal basis.

The plot below shows the chance that at least one person is infected in a subset of people, depending on the number of people in the subset. It shows three scenarios - the reported percentage of people infected, the percentage assuming cases are undercounted 5x, and the percentage assuming cases are undercounted 10x. 

```{r}
calculate_risk <- function(f_inf, n){
  1-(1-f_inf)^n
}

df_grid <- expand_grid(f_inf = c(county_f_inf_rep, county_f_inf_rep*5, county_f_inf_rep*10), n = seq(0, 250, 10))

df_calc <- df_grid %>% 
  mutate(risk = calculate_risk(f_inf, n)) %>% 
  mutate(tooltip = paste("If ",percent(f_inf)," of people are infected,",
                         '\n', "for a group of ",n, " people,",
                         '\n', "there is a ", percent(risk), " chance that\nat least 1 person is infected.",
                         sep = '')) %>% 
  mutate(id = paste(f_inf,n,sep='-'))

n100_rep <- (df_calc %>% filter(n==100 & f_inf == county_f_inf_rep))$risk
n100_5x <- (df_calc %>% filter(n==100 & f_inf == county_f_inf_rep*5))$risk
n100_10x <- (df_calc %>% filter(n==100 & f_inf == county_f_inf_rep*10))$risk

legend_labels <- c(paste0("Reported (", percent(county_f_inf_rep), ")"), 
                   paste0("5x (", percent(county_f_inf_rep*5), ")"),
                   paste0("10x (", percent(county_f_inf_rep*10), ")"))

p1 <- ggplot(df_calc, aes(x = n , y = risk, color = factor(percent(f_inf)), fill = factor(percent(f_inf)))) + 
  geom_path() + 
  geom_point_interactive(aes(tooltip = tooltip, data_id = id), shape = 21, color = 'black') + theme_bw() + 
  scale_y_continuous(labels = percent)+
  scale_color_viridis_d(name = 'Percentage of county\nrecently infected', labels = legend_labels)+ 
  scale_fill_viridis_d(name = 'Percentage of county\nrecently infected', labels = legend_labels) +
  labs(title = paste0('What is the chance of someone being infected\nfor different scenarios in ',params$county_name,' county?'), 
       x = 'Number of people in a group', y = 'Chance at least 1 person is infected') + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = 'bottom')

tooltip_css <- "background-color:LightGray;padding:10px;border-style:solid;border-color:black;border-width:1px;color:black;"

girafe(ggobj = p1,  options = list(opts_hover(css = "fill:black;"), 
                                  opts_tooltip(css = tooltip_css, opacity = 1), 
                                  opts_selection(type = 'none'),
                                  opts_sizing(rescale = T, width = 0.7))
)

```

For example, if we expect to see 100 people at the grocery store in `r params$county_name` county, what is the chance someone in the store is infected? 

* If all of the true cases are reported, then the chance is **`r percent(n100_rep)`.**
* If true cases are 5x higher, then the chance is **`r percent(n100_5x)`.**
* If true cases are 10x higher, then the chance is **`r percent(n100_10x)`.**

We can't know what the true chance is, but hopefully this back of the envelope calculation helps you to think about some common scenarios in a reasonable way.

## The chance is rarely zero.

---

What conclusions can we draw from this data? For most counties, there seems to be a low percentage of people infected. However, as we run into more and more people, the chance that we are encountering infected people is rarely zero. Often it is actually quite likely. Therefore, the safest assumption is that we are interacting with infected people whenever we see more than a few people. 

What can we do? People will make their own decisions, but there are some clear actions that we can take to minimize our risk.

1. **Continue to physically distance.** The fewer people we interact with the lower the risk. Especially avoid large groups of people in tight spaces.
2. **When we must interact with people, we should assume someone is infected.** That means taking reasonable precautions like wearing facemasks, washing hands, and keeping as much distance as possible.

Things may seem normal, but continue to stay vigilant. Good luck.

-----

<center>
Project by [Scott H. Saunders](https://scott-saunders.github.io/website/)
<br>
Code available here: [github repository](https://github.com/scott-saunders/covid_risk_calculator)
<br>
</center>
